apiVersion: v1
kind: deployable-architecture
metadata:
  name: vibe-code-landing-zone
  displayName: Vibe Code Landing Zone
  description: "Paste your vibe, exhale, and ship — a static site on IBM Cloud Object Storage (website enabled)."
  version: 1.0.1
spec:
  deliveryMethod: terraform
  entrypoint: main.tf
  runtime:
    name: terraform
    version: '1.5'
  variables: variables.tf
